services:
  app:
    build:
      context: .
    init: true
    restart: unless-stopped
    ports:
      - "2275:2275"
    depends_on: []
    # env_file: ./.env  # Uncomment if .env file exists
    environment:
      NODE_ENV: production
    volumes:
      - TempoDatabases:/tempodb
networks:
  default:
    name: app_network
volumes:
  TempoDatabases: